# Generated by Django 2.1.5 on 2019-01-31 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PA',
            fields=[
                ('stud_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PA_GIUSTIFICAZIONI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giust_id', models.CharField(max_length=40)),
                ('data', models.DateField()),
                ('nota', models.CharField(max_length=200)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interrogazioni_app.PA')),
            ],
        ),
        migrations.CreateModel(
            name='PA_INTERROGAZIONI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_id', models.CharField(max_length=40)),
                ('voto', models.CharField(max_length=10)),
                ('nota', models.CharField(max_length=300)),
                ('data', models.DateField()),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interrogazioni_app.PA')),
            ],
        ),
    ]
