# Generated by Django 2.1.5 on 2019-01-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interrogazioni_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pa_giustificazioni',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pa_interrogazioni',
            name='id',
        ),
        migrations.AlterField(
            model_name='pa_giustificazioni',
            name='giust_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pa_interrogazioni',
            name='inter_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
