# Generated by Django 2.1.5 on 2019-01-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interrogazioni_app', '0002_auto_20190131_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM',
            fields=[
                ('stud_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PM_GIUSTIFICAZIONI',
            fields=[
                ('giust_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('nota', models.CharField(max_length=200)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interrogazioni_app.PM')),
            ],
        ),
        migrations.CreateModel(
            name='PM_INTERROGAZIONI',
            fields=[
                ('inter_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('voto', models.CharField(max_length=10)),
                ('nota', models.CharField(max_length=300)),
                ('data', models.DateField()),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interrogazioni_app.PM')),
            ],
        ),
    ]
