from interrogazioni_app.models import PA, PM

def fill_PA ():
	alunno=PA(stud_id=1, nome="Elena", cognome=	"Agostini")
	alunno.save()
	alunno=PA(stud_id=2, nome="Pietro", cognome=	"Anesin")
	alunno.save()
	alunno=PA(stud_id=3, nome="Luca", cognome=	"Bonvecchio")
	alunno.save()
	alunno=PA(stud_id=4, nome="Chiara", cognome=	"Bragnagna")
	alunno.save()
	alunno=PA(stud_id=5, nome="Tommaso", cognome=	"Dal Rì")
	alunno.save()
	alunno=PA(stud_id=6, nome="Mauro", cognome= "	Dallapiccola")
	alunno.save()
	alunno=PA(stud_id=7, nome="Sofia", cognome=	"Degaspari")
	alunno.save()
	alunno=PA(stud_id=8, nome="Manar", cognome=	"El Hali")
	alunno.save()
	alunno=PA(stud_id=9, nome="Davide", cognome= "	Fontanari")
	alunno.save()
	alunno=PA(stud_id=10, nome="Riccardo", cognome=	"Furlan")
	alunno.save()
	alunno=PA(stud_id=11, nome="Alessandro", cognome=	"Gremes")
	alunno.save()
	alunno=PA(stud_id=12, nome="Marco", cognome=	"Mattevi")
	alunno.save()
	alunno=PA(stud_id=13, nome="Simone", cognome=	"Mosaner")
	alunno.save()
	alunno=PA(stud_id=14, nome="Samuele", cognome=	"Moser")
	alunno.save()
	alunno=PA(stud_id=15, nome="Loris", cognome=	"Orsingher")
	alunno.save()
	alunno=PA(stud_id=16, nome="Tommaso", cognome=	"Palazzini")
	alunno.save()
	alunno=PA(stud_id=17, nome="Tommaso", cognome=	"Piffer")
	alunno.save()
	alunno=PA(stud_id=18, nome="David", cognome=	"Pizzarro")
	alunno.save()
	alunno=PA(stud_id=19, nome="Lorenzo", cognome=	"Ravanelli")
	alunno.save()
	alunno=PA(stud_id=20, nome="Simone", cognome=	"Sandonà")
	alunno.save()
	alunno=PA(stud_id=21, nome="Erik", cognome=	"Tapparelli")
	alunno.save()
	alunno=PA(stud_id=22, nome="Gabriele", cognome=	"Tomelin")
	alunno.save()
	alunno=PA(stud_id=23, nome="Christian", cognome=	"Wieczerzynski")
	alunno.save()

def fill_PM():
	alunno=PM(stud_id=1, nome="Damiano", cognome="Baldessari")
	alunno.save()
	alunno=PM(stud_id=2, nome="Leonardo", cognome="Casasola")
	alunno.save()
	alunno=PM(stud_id=3, nome="Nicolò", cognome="Cellana")
	alunno.save()
	alunno=PM(stud_id=4, nome="Federico", cognome="Conci")
	alunno.save()
	alunno=PM(stud_id=5, nome="Tiziano", cognome="Dalrì")
	alunno.save()
	alunno=PM(stud_id=6, nome="Tommaso", cognome="Degasperi")
	alunno.save()
	alunno=PM(stud_id=7, nome="Lorenzo", cognome="Denardi")
	alunno.save()
	alunno=PM(stud_id=8, nome="Davide", cognome="Dolzan")
	alunno.save()
	alunno=PM(stud_id=9, nome="Giulio", cognome="Galler")
	alunno.save()
	alunno=PM(stud_id=10, nome="Matteo", cognome="Grassi")
	alunno.save()
	alunno=PM(stud_id=11, nome="Daniel", cognome="Graziadei")
	alunno.save()
	alunno=PM(stud_id=12, nome="Giuliano", cognome="Holler")
	alunno.save()
	alunno=PM(stud_id=13, nome="Manuel", cognome="Larcher")
	alunno.save()
	alunno=PM(stud_id=14, nome="Dennis", cognome="Mattevi")
	alunno.save()
	alunno=PM(stud_id=15, nome="Daniele", cognome="Mirizzi")
	alunno.save()
	alunno=PM(stud_id=16, nome="Mirco", cognome="Morelli")
	alunno.save()
	alunno=PM(stud_id=17, nome="Daniele", cognome="Negriolli")
	alunno.save()
	alunno=PM(stud_id=18, nome="Daniel", cognome="Pasquazzo")
	alunno.save()
	alunno=PM(stud_id=19, nome="Luca", cognome="Pisoni")
	alunno.save()
	alunno=PM(stud_id=20, nome="Valentino", cognome="Postica")
	alunno.save()
	alunno=PM(stud_id=21, nome="Pietro", cognome="Ropelato")
	alunno.save()
	alunno=PM(stud_id=22, nome="Simone", cognome="Smider")
	alunno.save()
	alunno=PM(stud_id=24, nome="Rey", cognome="Zuccati")
	alunno.save()
